package webtest;
// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.*;

public class testpichau {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(5000));
        driver.manage().window().maximize();
    }
    @AfterMethod
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void pichau() {
        driver.get("https://www.pichau.com.br/");

        {
            WebElement element = driver.findElement(By.cssSelector(".jss10"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".jss20")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".MuiList-root:nth-child(4) > .MuiListItem-root:nth-child(3) .MuiTypography-root")).click();
        driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .MuiListItem-root:nth-child(1) .MuiTypography-root")).click();
        driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .jss16 .jss162")).click();
        js.executeScript("window.scrollTo(0,89)");
        js.executeScript("window.scrollTo(0,401)");
        {
            WebElement element = driver.findElement(By.cssSelector(".jss290"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".jss290")).click();
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".jss20")).click();
        driver.findElement(By.cssSelector(".MuiList-root:nth-child(4) > .MuiListItem-root:nth-child(3) .MuiTypography-root")).click();
        driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .MuiListItem-root:nth-child(1) .MuiTypography-root")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .MuiListItem-root:nth-child(1) .MuiTypography-root"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .jss16 .jss465"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) .jss465")).click();
        js.executeScript("window.scrollTo(0,100)");
        js.executeScript("window.scrollTo(0,382)");
        {
            WebElement element = driver.findElement(By.cssSelector(".jss569 > small"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".jss569 > small")).click();
        js.executeScript("window.scrollTo(0,0)");
        assertThat(driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(1) .text-dark")).getText(), is("Computador Pichau Gamer, Intel i5-8500, GeForce GTX 1050 Ti 4GB, 8GB DDR4, SSD 240GB"));
        js.executeScript("window.scrollTo(0,77)");
        assertThat(driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(1) > .MuiTableCell-body:nth-child(4)")).getText(), is("1 x R$ 2.341,06"));
        js.executeScript("window.scrollTo(0,401)");
        assertThat(driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(4)")).getText(), is("1 x R$ 1.917,53"));
        driver.close();
    }
}
